version: '3.7'

services:
  traefik:
    image: aunited/traefik:sy
    command: --api --docker
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
      traefik:
        ipv4_address: 172.16.101.99

  yarn:
    image: node:13-alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - modules:/workspace/node_modules
      - yarncache:/workspace/.yarn-cache
    environment:
      - YARN_CACHE_FOLDER=/workspace/.yarn-cache
    entrypoint: yarn

  identity:
    image: node:13-alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - modules:/workspace/node_modules
    entrypoint: yarn run identity:dev
    depends_on:
      - db
      - rabbitmq
    ports:
      - 3002:50051

  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 3001:5432

  rabbitmq:
    image: rabbitmq:3.8.3-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  private-gateway:
    image: node:13-alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - modules:/workspace/node_modules
    entrypoint: yarn run private-gateway:dev
    labels:
      - 'traefik.frontend.rule=Host:private-gateway.sy.local.aunited.dev'
      - 'traefik.protocol=http'
      - 'traefik.port=3000'

volumes:
  modules:
  yarncache:

networks:
  traefik:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.101.0/24
