apiVersion: v1
kind: Service
metadata:
  name: '{{ template "static-app.fullname" . }}'
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    app: '{{ template "static-app.fullname" . }}'
spec:
  selector:
    app: '{{ template "static-app.fullname" . }}'
  ports:
    - port: 80
      name: http
      targetPort: nginx-http
  type: NodePort
