apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.name }}
  name: '{{ .Values.service.name }}'
  {{- else }}
  name: '{{ template "grpc-service.name" . }}'
  {{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: '{{ template "grpc-service.name" . }}'
spec:
  selector:
    app: {{ template "grpc-service.fullname" . }}
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: grpc
